name: PHP Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-stan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2']
    steps:
     - name: Install PHP 7.2
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php-versions }}
         ini-values: "post_max_size=256M" #optional
         
     - name: Install prestashop                              
       run: |
         wget https://github.com/PrestaShop/PrestaShop/releases/download/1.7.7.7/prestashop_1.7.7.7.zip
         unzip prestashop_1.7.7.7.zip
         unzip prestashop.zip -d prestashop
         rm prestashop.zip prestashop_1.7.7.7.zip
     - run: mkdir prestashop/modules/altapay
     - uses: actions/checkout@v2 
       with:
          path: prestashop/modules/altapay
       #working-directory: prestashop/modules/altapay
     - name: Install and run PhpCsFixer
       run: |
         composer install --no-interaction
         php vendor/bin/php-cs-fixer fix --dry-run --diff
       working-directory: prestashop/modules/altapay

     - name: Composer dependency isolation
       if: ${{ always() }}
       run: |
         yes | vendor/bin/php-scoper add-prefix
         rsync -a build/vendor/* vendor/ && rm -rf build/
         composer dump-autoload --working-dir ./ --classmap-authoritative --no-interaction
         _PS_ROOT_DIR_=../../ php vendor/phpstan/phpstan/phpstan.phar --configuration=phpstan.neon analyse ./
       working-directory: prestashop/modules/altapay
       
     - name: Install PHP 7.0
       uses: shivammathur/setup-php@v2
       with:
         php-version: '7.0'
         extensions: intl #optional
         ini-values: "post_max_size=256M" #optional

     - name: Run php7.0 linter
       run: |
         find . -path ./vendor -prune -false -o -type f -name '*.php' -print0 | xargs -0 -n1 -P$(nproc) php7.0 -l -n | (! grep -v "No syntax errors detected" )
       working-directory: prestashop/modules/altapay
